// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using post_office_back.Data;

#nullable disable

namespace post_office_back.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240604082726_ChangeBagTypeToString")]
    partial class ChangeBagTypeToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("post_office_back.Models.Bag", b =>
                {
                    b.Property<string>("BagNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BagType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountOfLetters")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("BagNumber");

                    b.HasIndex("ShipmentNumber");

                    b.ToTable("Bags");
                });

            modelBuilder.Entity("post_office_back.Models.Parcel", b =>
                {
                    b.Property<string>("ParcelNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParcelBagBagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ParcelNumber");

                    b.HasIndex("ParcelBagBagNumber");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("post_office_back.Models.Shipment", b =>
                {
                    b.Property<string>("ShipmentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.HasKey("ShipmentNumber");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("post_office_back.Models.Bag", b =>
                {
                    b.HasOne("post_office_back.Models.Shipment", "Shipment")
                        .WithMany("Bags")
                        .HasForeignKey("ShipmentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("post_office_back.Models.Parcel", b =>
                {
                    b.HasOne("post_office_back.Models.Bag", "ParcelBag")
                        .WithMany("Parcels")
                        .HasForeignKey("ParcelBagBagNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelBag");
                });

            modelBuilder.Entity("post_office_back.Models.Bag", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("post_office_back.Models.Shipment", b =>
                {
                    b.Navigation("Bags");
                });
#pragma warning restore 612, 618
        }
    }
}
